# Generated by Django 3.2.1 on 2021-05-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
